use std::collections::HashMap;
use std::sync::{Arc, Mutex};

use gst::prelude::*;
use gstreamer as gst;
use gstreamer_sdp as gst_sdp;
use gstreamer_webrtc::{
    WebRTCDataChannel, WebRTCDataChannelState, WebRTCSDPType, WebRTCSessionDescription,
};

use super::channel::{ChannelError, DataChannelSpec};
use super::envelope::MessageEnvelope;

/// Events generated by `webrtcbin` that must be carried by an authenticated
/// DeskLink signaling path. SDP and ICE never bypass the existing paired link.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PeerEvent {
    Offer(String),
    Answer(String),
    IceCandidate { mline_index: u32, candidate: String },
    EndOfCandidates,
    ControlChannelOpen,
    Failure(String),
}

pub type PeerEventSink = Arc<dyn Fn(PeerEvent) + Send + Sync>;

/// A GLib/GStreamer owned WebRTC peer. The owner is deliberately small: it
/// negotiates the fixed DeskLink data-channel contract and delegates all
/// signaling to the paired-session coordinator.
pub struct PeerConnection {
    element: gst::Element,
    pipeline: Option<gst::Pipeline>,
    channels: Arc<Mutex<HashMap<String, WebRTCDataChannel>>>,
    events: Option<PeerEventSink>,
}

impl PeerConnection {
    /// Construct a non-negotiating peer wrapper for capability checks/tests.
    pub fn new(element: gst::Element) -> Self {
        Self {
            element,
            pipeline: None,
            channels: Arc::new(Mutex::new(HashMap::new())),
            events: None,
        }
    }

    /// Construct a running data-channel-only peer connection. The pipeline is
    /// required: `webrtcbin` does not produce SDP or ICE while detached.
    pub fn new_negotiated(events: PeerEventSink) -> Result<Self, String> {
        gst::init().map_err(|error| error.to_string())?;
        let element = gst::ElementFactory::make("webrtcbin")
            .name("desklink-webrtcbin")
            .build()
            .map_err(|error| error.to_string())?;
        let pipeline = gst::Pipeline::new();
        pipeline.add(&element).map_err(|error| error.to_string())?;
        let peer = Self {
            element,
            pipeline: Some(pipeline),
            channels: Arc::new(Mutex::new(HashMap::new())),
            events: Some(events),
        };
        peer.attach_webrtc_callbacks();
        peer.pipeline
            .as_ref()
            .expect("negotiated peer owns a pipeline")
            .set_state(gst::State::Playing)
            .map_err(|error| error.to_string())?;
        Ok(peer)
    }

    pub fn element(&self) -> &gst::Element {
        &self.element
    }

    pub fn create_channels(&self) -> Result<(), ChannelError> {
        for spec in DataChannelSpec::all() {
            let mut options =
                gst::Structure::builder("desklink-data-channel").field("ordered", spec.ordered);
            if let Some(max_retransmits) = spec.max_retransmits {
                options = options.field("max-retransmits", i32::from(max_retransmits));
            }
            if let Some(channel) = self.element.emit_by_name::<Option<WebRTCDataChannel>>(
                "create-data-channel",
                &[&spec.label, &Some(options.build())],
            ) {
                self.install_channel(channel)?;
            } else {
                return Err(ChannelError::UnknownLabel(spec.label.to_string()));
            }
        }
        Ok(())
    }

    pub fn start_offer(&self) -> Result<(), String> {
        let events = self
            .events
            .clone()
            .ok_or_else(|| "WebRTC peer has no signaling event sink".to_string())?;
        let element = self.element.clone();
        let promise = gst::Promise::with_change_func(move |reply| {
            let result: Result<String, String> = (|| {
                let reply = reply.map_err(|error| format!("{error:?}"))?;
                let reply = reply.ok_or_else(|| "create-offer returned no SDP".to_string())?;
                let offer: WebRTCSessionDescription =
                    reply.get("offer").map_err(|error| error.to_string())?;
                let sdp = offer.sdp().as_text().map_err(|error| error.to_string())?;
                element
                    .emit_by_name::<()>("set-local-description", &[&offer, &None::<gst::Promise>]);
                Ok(sdp)
            })();
            match result {
                Ok(sdp) => events(PeerEvent::Offer(sdp)),
                Err(error) => events(PeerEvent::Failure(format!(
                    "could not create offer: {error}"
                ))),
            }
        });
        self.element
            .emit_by_name::<()>("create-offer", &[&None::<gst::Structure>, &promise]);
        Ok(())
    }

    pub fn accept_offer_and_create_answer(&self, sdp: &str) -> Result<(), String> {
        self.set_remote_description(WebRTCSDPType::Offer, sdp)?;
        let events = self
            .events
            .clone()
            .ok_or_else(|| "WebRTC peer has no signaling event sink".to_string())?;
        let element = self.element.clone();
        let promise = gst::Promise::with_change_func(move |reply| {
            let result: Result<String, String> = (|| {
                let reply = reply.map_err(|error| format!("{error:?}"))?;
                let reply = reply.ok_or_else(|| "create-answer returned no SDP".to_string())?;
                let answer: WebRTCSessionDescription =
                    reply.get("answer").map_err(|error| error.to_string())?;
                let sdp = answer.sdp().as_text().map_err(|error| error.to_string())?;
                element
                    .emit_by_name::<()>("set-local-description", &[&answer, &None::<gst::Promise>]);
                Ok(sdp)
            })();
            match result {
                Ok(sdp) => events(PeerEvent::Answer(sdp)),
                Err(error) => events(PeerEvent::Failure(format!(
                    "could not create answer: {error}"
                ))),
            }
        });
        self.element
            .emit_by_name::<()>("create-answer", &[&None::<gst::Structure>, &promise]);
        Ok(())
    }

    pub fn accept_answer(&self, sdp: &str) -> Result<(), String> {
        self.set_remote_description(WebRTCSDPType::Answer, sdp)
    }

    pub fn add_ice_candidate(&self, mline_index: u32, candidate: &str) -> Result<(), String> {
        if candidate.len() > 16 * 1024 {
            return Err("WebRTC ICE candidate exceeds 16 KiB".to_string());
        }
        self.element
            .emit_by_name::<()>("add-ice-candidate", &[&mline_index, &candidate]);
        Ok(())
    }

    fn set_remote_description(&self, kind: WebRTCSDPType, sdp: &str) -> Result<(), String> {
        if sdp.is_empty() || sdp.len() > 256 * 1024 {
            return Err("WebRTC SDP is empty or exceeds 256 KiB".to_string());
        }
        let sdp = gst_sdp::SDPMessage::parse_buffer(sdp.as_bytes())
            .map_err(|error| format!("invalid WebRTC SDP: {error}"))?;
        let description = WebRTCSessionDescription::new(kind, sdp);
        self.element.emit_by_name::<()>(
            "set-remote-description",
            &[&description, &None::<gst::Promise>],
        );
        Ok(())
    }

    pub fn channel_state(&self, label: &str) -> Option<WebRTCDataChannelState> {
        self.channels
            .lock()
            .ok()
            .and_then(|channels| channels.get(label).map(WebRTCDataChannel::ready_state))
    }

    pub fn send(&self, label: &str, payload: &[u8]) -> Result<(), String> {
        let channel = self
            .channels
            .lock()
            .map_err(|_| "WebRTC channel map poisoned".to_string())?
            .get(label)
            .cloned()
            .ok_or_else(|| format!("unknown WebRTC data channel: {label}"))?;
        if channel.ready_state() != WebRTCDataChannelState::Open {
            return Err(format!("WebRTC data channel is not open: {label}"));
        }
        channel
            .send_data_full(Some(&gst::glib::Bytes::from(payload)))
            .map_err(|error| error.to_string())
    }

    pub fn send_envelope(
        &self,
        channel: &DataChannelSpec,
        envelope: &MessageEnvelope,
    ) -> Result<(), String> {
        if envelope.channel != channel.label {
            return Err(format!(
                "WebRTC envelope channel does not match data channel: {}",
                channel.label
            ));
        }
        let bytes = serde_json::to_vec(envelope).map_err(|error| error.to_string())?;
        self.send(channel.label, &bytes)
    }

    pub fn attach_message_handler<F>(&self, label: &str, handler: F) -> Result<(), String>
    where
        F: Fn(&[u8]) + Send + Sync + 'static,
    {
        let channel = self
            .channels
            .lock()
            .map_err(|_| "WebRTC channel map poisoned".to_string())?
            .get(label)
            .cloned()
            .ok_or_else(|| format!("unknown WebRTC data channel: {label}"))?;
        channel.connect_on_message_data(move |_, bytes| {
            if let Some(bytes) = bytes {
                handler(bytes.as_ref());
            }
        });
        Ok(())
    }

    fn attach_webrtc_callbacks(&self) {
        let events = self.events.clone();
        self.element
            .connect("on-ice-candidate", false, move |values| {
                let mline_index = values.get(1).and_then(|value| value.get::<u32>().ok());
                let candidate = values.get(2).and_then(|value| value.get::<String>().ok());
                if let (Some(mline_index), Some(candidate), Some(events)) =
                    (mline_index, candidate, events.as_ref())
                {
                    events(PeerEvent::IceCandidate {
                        mline_index,
                        candidate,
                    });
                }
                None
            });

        let events = self.events.clone();
        self.element.connect("on-data-channel", false, {
            let channels = Arc::clone(&self.channels);
            move |values| {
                let channel = values
                    .get(1)
                    .and_then(|value| value.get::<WebRTCDataChannel>().ok());
                if let Some(channel) = channel {
                    if let Err(error) = install_channel_into(&channels, events.clone(), channel) {
                        if let Some(events) = events.as_ref() {
                            events(PeerEvent::Failure(format!(
                                "rejected remote data channel: {error}"
                            )));
                        }
                    }
                }
                None
            }
        });
    }

    fn install_channel(&self, channel: WebRTCDataChannel) -> Result<(), ChannelError> {
        install_channel_into(&self.channels, self.events.clone(), channel)
    }

    pub fn close(&self) {
        if let Ok(channels) = self.channels.lock() {
            for channel in channels.values() {
                channel.close();
            }
        }
        if let Some(pipeline) = &self.pipeline {
            let _ = pipeline.set_state(gst::State::Null);
        }
        let _ = self.element.set_state(gst::State::Null);
    }
}

fn install_channel_into(
    channels: &Arc<Mutex<HashMap<String, WebRTCDataChannel>>>,
    events: Option<PeerEventSink>,
    channel: WebRTCDataChannel,
) -> Result<(), ChannelError> {
    let label = channel
        .label()
        .map(|label| label.to_string())
        .ok_or_else(|| ChannelError::UnknownLabel("missing label".to_string()))?;
    let retransmits = match channel.max_retransmits() {
        -1 => None,
        value => Some(
            u16::try_from(value).map_err(|_| ChannelError::InvalidReliability(label.clone()))?,
        ),
    };
    DataChannelSpec::validate_remote(&label, channel.is_ordered(), retransmits)?;
    let open_events = events.clone();
    let open_label = label.clone();
    channel.connect_on_open(move |_| {
        if open_label == DataChannelSpec::CONTROL.label {
            if let Some(events) = open_events.as_ref() {
                events(PeerEvent::ControlChannelOpen);
            }
        }
    });
    let error_label = label.clone();
    channel.connect_on_error(move |_, error| {
        if let Some(events) = events.as_ref() {
            events(PeerEvent::Failure(format!(
                "data channel {error_label} failed: {error}"
            )));
        }
    });
    channels
        .lock()
        .map_err(|_| ChannelError::UnknownLabel("channel map poisoned".to_string()))?
        .insert(label, channel);
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::mpsc;
    use std::time::{Duration, Instant};

    #[test]
    fn webrtcbin_is_available_on_this_runtime() {
        gst::init().unwrap();
        let element = gst::ElementFactory::make("webrtcbin")
            .name("desklink-test-webrtcbin")
            .build()
            .expect("GStreamer WebRTC plugin is required by desktop builds");
        let peer = PeerConnection::new(element);
        // Channel creation belongs to an active, negotiated pipeline. The
        // construction test keeps CI independent of a live network peer.
        peer.close();
    }

    #[test]
    fn rejects_oversized_sdp_before_gstreamer_parses_it() {
        let element = gst::ElementFactory::make("webrtcbin").build().unwrap();
        let peer = PeerConnection::new(element);
        assert!(peer.accept_answer(&"x".repeat(256 * 1024 + 1)).is_err());
    }

    /// Native runtime smoke test for the exact SDP/ICE/data-channel callbacks
    /// used by the desktop coordinator. It is opt-in because it opens local
    /// ICE sockets and requires the installed GStreamer WebRTC runtime.
    #[test]
    #[ignore = "requires a native GStreamer WebRTC loopback runtime"]
    fn desktop_data_channels_negotiate_over_loopback() {
        let (sender, receiver) = mpsc::channel::<(char, PeerEvent)>();
        let initiator_sender = sender.clone();
        let initiator = Arc::new(
            PeerConnection::new_negotiated(Arc::new(move |event| {
                let _ = initiator_sender.send(('a', event));
            }))
            .unwrap(),
        );
        let responder_sender = sender.clone();
        let responder = Arc::new(
            PeerConnection::new_negotiated(Arc::new(move |event| {
                let _ = responder_sender.send(('b', event));
            }))
            .unwrap(),
        );

        initiator.create_channels().unwrap();
        initiator.start_offer().unwrap();

        let mut initiator_open = false;
        let mut responder_open = false;
        let deadline = Instant::now() + Duration::from_secs(15);
        while Instant::now() < deadline && !(initiator_open && responder_open) {
            let Ok((side, event)) = receiver.recv_timeout(Duration::from_millis(250)) else {
                continue;
            };
            match (side, event) {
                ('a', PeerEvent::Offer(sdp)) => {
                    responder.accept_offer_and_create_answer(&sdp).unwrap()
                }
                ('b', PeerEvent::Answer(sdp)) => initiator.accept_answer(&sdp).unwrap(),
                (
                    'a',
                    PeerEvent::IceCandidate {
                        mline_index,
                        candidate,
                    },
                ) => responder
                    .add_ice_candidate(mline_index, &candidate)
                    .unwrap(),
                (
                    'b',
                    PeerEvent::IceCandidate {
                        mline_index,
                        candidate,
                    },
                ) => initiator
                    .add_ice_candidate(mline_index, &candidate)
                    .unwrap(),
                ('a', PeerEvent::ControlChannelOpen) => initiator_open = true,
                ('b', PeerEvent::ControlChannelOpen) => responder_open = true,
                (_, PeerEvent::EndOfCandidates) => {}
                (_, PeerEvent::Failure(error)) => panic!("native WebRTC loopback failed: {error}"),
                _ => {}
            }
        }
        initiator.close();
        responder.close();
        assert!(
            initiator_open && responder_open,
            "WebRTC control channel did not open before the loopback deadline"
        );
    }
}
