use std::collections::HashMap;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::{Arc, Mutex};
use std::thread;
use std::time::Duration;

use gst::prelude::*;
use gstreamer as gst;
use gstreamer_app::{AppSink, AppSinkCallbacks, AppSrc};
use gstreamer_sdp as gst_sdp;
use gstreamer_webrtc::{
    WebRTCDataChannel, WebRTCDataChannelState, WebRTCPeerConnectionState, WebRTCSDPType,
    WebRTCSessionDescription,
};

use super::channel::{ChannelError, DataChannelSpec};
use super::envelope::MessageEnvelope;

/// Events generated by `webrtcbin` that must be carried by an authenticated
/// DeskLink signaling path. SDP and ICE never bypass the existing paired link.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PeerEvent {
    Offer(String),
    Answer(String),
    IceCandidate {
        mline_index: u32,
        candidate: String,
    },
    EndOfCandidates,
    ControlChannelOpen,
    Message {
        channel: String,
        bytes: Vec<u8>,
    },
    VideoFrame {
        sequence: u64,
        width: u32,
        height: u32,
        rgba: Vec<u8>,
    },
    Connected,
    Disconnected,
    Failure(String),
}

pub type PeerEventSink = Arc<dyn Fn(PeerEvent) + Send + Sync>;

/// A GLib/GStreamer owned WebRTC peer. The owner is deliberately small: it
/// negotiates the fixed DeskLink data-channel contract and delegates all
/// signaling to the paired-session coordinator.
pub struct PeerConnection {
    element: gst::Element,
    pipeline: Option<gst::Pipeline>,
    channels: Arc<Mutex<HashMap<String, WebRTCDataChannel>>>,
    events: Option<PeerEventSink>,
    video_source: Arc<Mutex<Option<AppSrc>>>,
    video_stop: Arc<Mutex<Option<Arc<AtomicBool>>>>,
    video_worker: Arc<Mutex<Option<thread::JoinHandle<()>>>>,
    video_sequence: Arc<AtomicU64>,
}

impl PeerConnection {
    /// Construct a non-negotiating peer wrapper for capability checks/tests.
    pub fn new(element: gst::Element) -> Self {
        Self {
            element,
            pipeline: None,
            channels: Arc::new(Mutex::new(HashMap::new())),
            events: None,
            video_source: Arc::new(Mutex::new(None)),
            video_stop: Arc::new(Mutex::new(None)),
            video_worker: Arc::new(Mutex::new(None)),
            video_sequence: Arc::new(AtomicU64::new(0)),
        }
    }

    /// Construct a running data-channel-only peer connection. The pipeline is
    /// required: `webrtcbin` does not produce SDP or ICE while detached.
    pub fn new_negotiated(events: PeerEventSink) -> Result<Self, String> {
        Self::new_negotiated_with_ice(events, &[], &[])
    }

    pub fn new_negotiated_with_ice(
        events: PeerEventSink,
        stun_servers: &[String],
        turn_servers: &[String],
    ) -> Result<Self, String> {
        gst::init().map_err(|error| error.to_string())?;
        let element = gst::ElementFactory::make("webrtcbin")
            .name("desklink-webrtcbin")
            .build()
            .map_err(|error| error.to_string())?;
        if let Some(stun) = stun_servers.first() {
            element.set_property("stun-server", stun);
        }
        for turn in turn_servers {
            if !element.emit_by_name::<bool>("add-turn-server", &[turn]) {
                return Err(format!("GStreamer rejected TURN server URI: {turn}"));
            }
        }
        let pipeline = gst::Pipeline::new();
        pipeline.add(&element).map_err(|error| error.to_string())?;
        let peer = Self {
            element,
            pipeline: Some(pipeline),
            channels: Arc::new(Mutex::new(HashMap::new())),
            events: Some(events),
            video_source: Arc::new(Mutex::new(None)),
            video_stop: Arc::new(Mutex::new(None)),
            video_worker: Arc::new(Mutex::new(None)),
            video_sequence: Arc::new(AtomicU64::new(0)),
        };
        // Install the receive/send VP8 media path before the first SDP offer.
        // If a runtime lacks one of the optional screen elements, ordinary
        // WebRTC control traffic remains usable and a screen request reports
        // the unavailable backend explicitly.
        let _ = peer.install_video_pipeline();
        peer.attach_webrtc_callbacks();
        peer.pipeline
            .as_ref()
            .expect("negotiated peer owns a pipeline")
            .set_state(gst::State::Playing)
            .map_err(|error| error.to_string())?;
        Ok(peer)
    }

    pub fn element(&self) -> &gst::Element {
        &self.element
    }

    fn install_video_pipeline(&self) -> Result<(), String> {
        let pipeline = self
            .pipeline
            .as_ref()
            .ok_or_else(|| "WebRTC screen media requires a running pipeline".to_string())?;
        if self
            .video_source
            .lock()
            .map_err(|_| "WebRTC video source lock poisoned".to_string())?
            .is_some()
        {
            return Ok(());
        }

        let raw_caps = gst::Caps::builder("video/x-raw")
            .field("format", "RGBA")
            .field("framerate", gst::Fraction::new(12, 1))
            .build();
        let source = AppSrc::builder()
            .name("desklink-screen-source")
            .caps(&raw_caps)
            .is_live(true)
            .format(gst::Format::Time)
            .max_buffers(2)
            .build();
        let convert = gst::ElementFactory::make("videoconvert")
            .name("desklink-screen-convert")
            .build()
            .map_err(|error| error.to_string())?;
        let encoder = gst::ElementFactory::make("vp8enc")
            .name("desklink-screen-vp8")
            .build()
            .map_err(|error| error.to_string())?;
        encoder.set_property("deadline", 1_i64);
        let payloader = gst::ElementFactory::make("rtpvp8pay")
            .name("desklink-screen-payloader")
            .build()
            .map_err(|error| error.to_string())?;

        pipeline
            .add_many([source.upcast_ref(), &convert, &encoder, &payloader])
            .map_err(|error| error.to_string())?;
        gst::Element::link_many([source.upcast_ref(), &convert, &encoder, &payloader])
            .map_err(|error| error.to_string())?;
        let sink_pad = self
            .element
            .request_pad_simple("sink_%u")
            .ok_or_else(|| "WebRTC peer did not expose a video sink pad".to_string())?;
        let payloader_src = payloader
            .static_pad("src")
            .ok_or_else(|| "VP8 payloader has no source pad".to_string())?;
        payloader_src
            .link(&sink_pad)
            .map_err(|error| format!("Could not link VP8 screen track: {error}"))?;
        source
            .upcast_ref::<gst::Element>()
            .sync_state_with_parent()
            .map_err(|error| error.to_string())?;
        convert
            .sync_state_with_parent()
            .map_err(|error| error.to_string())?;
        encoder
            .sync_state_with_parent()
            .map_err(|error| error.to_string())?;
        payloader
            .sync_state_with_parent()
            .map_err(|error| error.to_string())?;
        *self
            .video_source
            .lock()
            .map_err(|_| "WebRTC video source lock poisoned".to_string())? = Some(source);
        Ok(())
    }

    pub fn start_screen_capture(&self) -> Result<(), String> {
        self.install_video_pipeline()?;
        self.stop_screen_capture();
        let source = self
            .video_source
            .lock()
            .map_err(|_| "WebRTC video source lock poisoned".to_string())?
            .clone()
            .ok_or_else(|| "WebRTC screen source is unavailable".to_string())?;
        let capture = crate::platform::screen_cast::ScreenCastCapture::new()?;
        let stop = Arc::new(AtomicBool::new(false));
        let worker_stop = Arc::clone(&stop);
        let worker = thread::Builder::new()
            .name("desklink-webrtc-screen".to_string())
            .spawn(move || {
                let mut sequence = 0_u64;
                while !worker_stop.load(Ordering::Relaxed) {
                    let Ok((rgba, width, height)) = capture.next_rgba(Duration::from_secs(3))
                    else {
                        break;
                    };
                    let caps = gst::Caps::builder("video/x-raw")
                        .field("format", "RGBA")
                        .field("width", width as i32)
                        .field("height", height as i32)
                        .field("framerate", gst::Fraction::new(12, 1))
                        .build();
                    source.set_caps(Some(&caps));
                    let Ok(mut buffer) = gst::Buffer::with_size(rgba.len()) else {
                        break;
                    };
                    let timestamp = gst::ClockTime::from_mseconds(sequence * 83);
                    {
                        let Some(buffer_ref) = buffer.get_mut() else {
                            break;
                        };
                        {
                            let Ok(mut map) = buffer_ref.map_writable() else {
                                break;
                            };
                            map.as_mut_slice().copy_from_slice(&rgba);
                        }
                        buffer_ref.set_pts(timestamp);
                        buffer_ref.set_dts(timestamp);
                        buffer_ref.set_duration(gst::ClockTime::from_mseconds(83));
                    }
                    if source.push_buffer(buffer).is_err() {
                        break;
                    }
                    sequence = sequence.saturating_add(1);
                }
            })
            .map_err(|error| format!("Could not start WebRTC screen capture: {error}"))?;
        *self
            .video_stop
            .lock()
            .map_err(|_| "WebRTC video stop lock poisoned".to_string())? = Some(stop);
        *self
            .video_worker
            .lock()
            .map_err(|_| "WebRTC video worker lock poisoned".to_string())? = Some(worker);
        Ok(())
    }

    pub fn stop_screen_capture(&self) {
        if let Ok(mut stop) = self.video_stop.lock() {
            if let Some(stop) = stop.take() {
                stop.store(true, Ordering::Relaxed);
            }
        }
        if let Ok(mut worker) = self.video_worker.lock() {
            if let Some(worker) = worker.take() {
                let _ = worker.join();
            }
        }
    }

    pub fn create_channels(&self) -> Result<(), ChannelError> {
        for spec in DataChannelSpec::all() {
            let mut options =
                gst::Structure::builder("desklink-data-channel").field("ordered", spec.ordered);
            if let Some(max_retransmits) = spec.max_retransmits {
                options = options.field("max-retransmits", i32::from(max_retransmits));
            }
            if let Some(channel) = self.element.emit_by_name::<Option<WebRTCDataChannel>>(
                "create-data-channel",
                &[&spec.label, &Some(options.build())],
            ) {
                self.install_channel(channel)?;
            } else {
                return Err(ChannelError::UnknownLabel(spec.label.to_string()));
            }
        }
        Ok(())
    }

    pub fn start_offer(&self) -> Result<(), String> {
        let events = self
            .events
            .clone()
            .ok_or_else(|| "WebRTC peer has no signaling event sink".to_string())?;
        let element = self.element.clone();
        let promise = gst::Promise::with_change_func(move |reply| {
            let result: Result<String, String> = (|| {
                let reply = reply.map_err(|error| format!("{error:?}"))?;
                let reply = reply.ok_or_else(|| "create-offer returned no SDP".to_string())?;
                let offer: WebRTCSessionDescription =
                    reply.get("offer").map_err(|error| error.to_string())?;
                let sdp = offer.sdp().as_text().map_err(|error| error.to_string())?;
                element
                    .emit_by_name::<()>("set-local-description", &[&offer, &None::<gst::Promise>]);
                Ok(sdp)
            })();
            match result {
                Ok(sdp) => events(PeerEvent::Offer(sdp)),
                Err(error) => events(PeerEvent::Failure(format!(
                    "could not create offer: {error}"
                ))),
            }
        });
        self.element
            .emit_by_name::<()>("create-offer", &[&None::<gst::Structure>, &promise]);
        Ok(())
    }

    pub fn accept_offer_and_create_answer(&self, sdp: &str) -> Result<(), String> {
        self.set_remote_description(WebRTCSDPType::Offer, sdp)?;
        let events = self
            .events
            .clone()
            .ok_or_else(|| "WebRTC peer has no signaling event sink".to_string())?;
        let element = self.element.clone();
        let promise = gst::Promise::with_change_func(move |reply| {
            let result: Result<String, String> = (|| {
                let reply = reply.map_err(|error| format!("{error:?}"))?;
                let reply = reply.ok_or_else(|| "create-answer returned no SDP".to_string())?;
                let answer: WebRTCSessionDescription =
                    reply.get("answer").map_err(|error| error.to_string())?;
                let sdp = answer.sdp().as_text().map_err(|error| error.to_string())?;
                element
                    .emit_by_name::<()>("set-local-description", &[&answer, &None::<gst::Promise>]);
                Ok(sdp)
            })();
            match result {
                Ok(sdp) => events(PeerEvent::Answer(sdp)),
                Err(error) => events(PeerEvent::Failure(format!(
                    "could not create answer: {error}"
                ))),
            }
        });
        self.element
            .emit_by_name::<()>("create-answer", &[&None::<gst::Structure>, &promise]);
        Ok(())
    }

    pub fn accept_answer(&self, sdp: &str) -> Result<(), String> {
        self.set_remote_description(WebRTCSDPType::Answer, sdp)
    }

    pub fn add_ice_candidate(&self, mline_index: u32, candidate: &str) -> Result<(), String> {
        if candidate.len() > 16 * 1024 {
            return Err("WebRTC ICE candidate exceeds 16 KiB".to_string());
        }
        self.element
            .emit_by_name::<()>("add-ice-candidate", &[&mline_index, &candidate]);
        Ok(())
    }

    fn set_remote_description(&self, kind: WebRTCSDPType, sdp: &str) -> Result<(), String> {
        if sdp.is_empty() || sdp.len() > 256 * 1024 {
            return Err("WebRTC SDP is empty or exceeds 256 KiB".to_string());
        }
        let sdp = gst_sdp::SDPMessage::parse_buffer(sdp.as_bytes())
            .map_err(|error| format!("invalid WebRTC SDP: {error}"))?;
        let description = WebRTCSessionDescription::new(kind, sdp);
        self.element.emit_by_name::<()>(
            "set-remote-description",
            &[&description, &None::<gst::Promise>],
        );
        Ok(())
    }

    pub fn channel_state(&self, label: &str) -> Option<WebRTCDataChannelState> {
        self.channels
            .lock()
            .ok()
            .and_then(|channels| channels.get(label).map(WebRTCDataChannel::ready_state))
    }

    pub fn send(&self, label: &str, payload: &[u8]) -> Result<(), String> {
        let channel = self
            .channels
            .lock()
            .map_err(|_| "WebRTC channel map poisoned".to_string())?
            .get(label)
            .cloned()
            .ok_or_else(|| format!("unknown WebRTC data channel: {label}"))?;
        if channel.ready_state() != WebRTCDataChannelState::Open {
            return Err(format!("WebRTC data channel is not open: {label}"));
        }
        channel
            .send_data_full(Some(&gst::glib::Bytes::from(payload)))
            .map_err(|error| error.to_string())
    }

    pub fn send_envelope(
        &self,
        channel: &DataChannelSpec,
        envelope: &MessageEnvelope,
    ) -> Result<(), String> {
        if envelope.channel != channel.label {
            return Err(format!(
                "WebRTC envelope channel does not match data channel: {}",
                channel.label
            ));
        }
        let bytes = serde_json::to_vec(envelope).map_err(|error| error.to_string())?;
        self.send(channel.label, &bytes)
    }

    pub fn attach_message_handler<F>(&self, label: &str, handler: F) -> Result<(), String>
    where
        F: Fn(&[u8]) + Send + Sync + 'static,
    {
        let channel = self
            .channels
            .lock()
            .map_err(|_| "WebRTC channel map poisoned".to_string())?
            .get(label)
            .cloned()
            .ok_or_else(|| format!("unknown WebRTC data channel: {label}"))?;
        channel.connect_on_message_data(move |_, bytes| {
            if let Some(bytes) = bytes {
                handler(bytes.as_ref());
            }
        });
        Ok(())
    }

    fn attach_webrtc_callbacks(&self) {
        let state_events = self.events.clone();
        self.element
            .connect_notify(Some("connection-state"), move |element, _| {
                let state = element.property::<WebRTCPeerConnectionState>("connection-state");
                let event = match state {
                    WebRTCPeerConnectionState::Connected => Some(PeerEvent::Connected),
                    WebRTCPeerConnectionState::Disconnected => Some(PeerEvent::Disconnected),
                    WebRTCPeerConnectionState::Failed => Some(PeerEvent::Failure(
                        "WebRTC peer connection failed".to_string(),
                    )),
                    _ => None,
                };
                if let (Some(events), Some(event)) = (state_events.as_ref(), event) {
                    events(event);
                }
            });

        let events = self.events.clone();
        self.element
            .connect("on-ice-candidate", false, move |values| {
                let mline_index = values.get(1).and_then(|value| value.get::<u32>().ok());
                let candidate = values.get(2).and_then(|value| value.get::<String>().ok());
                if let (Some(mline_index), Some(candidate), Some(events)) =
                    (mline_index, candidate, events.as_ref())
                {
                    events(PeerEvent::IceCandidate {
                        mline_index,
                        candidate,
                    });
                }
                None
            });

        let events = self.events.clone();
        self.element.connect("on-data-channel", false, {
            let channels = Arc::clone(&self.channels);
            move |values| {
                let channel = values
                    .get(1)
                    .and_then(|value| value.get::<WebRTCDataChannel>().ok());
                if let Some(channel) = channel {
                    if let Err(error) = install_channel_into(&channels, events.clone(), channel) {
                        if let Some(events) = events.as_ref() {
                            events(PeerEvent::Failure(format!(
                                "rejected remote data channel: {error}"
                            )));
                        }
                    }
                }
                None
            }
        });

        let Some(pipeline) = self.pipeline.clone() else {
            return;
        };
        let events = self.events.clone();
        let frame_sequence = Arc::clone(&self.video_sequence);
        self.element.connect_pad_added(move |_, pad| {
            let Some(caps) = pad.current_caps().or_else(|| Some(pad.query_caps(None))) else {
                return;
            };
            let Some(structure) = caps.structure(0) else {
                return;
            };
            if structure.name() != "application/x-rtp"
                || structure.get::<String>("media").ok().as_deref() != Some("video")
            {
                return;
            }

            let result = (|| -> Result<(), String> {
                let frame_sequence = Arc::clone(&frame_sequence);
                let depay = gst::ElementFactory::make("rtpvp8depay")
                    .name("desklink-screen-depay")
                    .build()
                    .map_err(|error| error.to_string())?;
                let decoder = gst::ElementFactory::make("vp8dec")
                    .name("desklink-screen-decoder")
                    .build()
                    .map_err(|error| error.to_string())?;
                let convert = gst::ElementFactory::make("videoconvert")
                    .name("desklink-screen-receive-convert")
                    .build()
                    .map_err(|error| error.to_string())?;
                let raw_caps = gst::Caps::builder("video/x-raw")
                    .field("format", "RGBA")
                    .build();
                let filter = gst::ElementFactory::make("capsfilter")
                    .property("caps", &raw_caps)
                    .build()
                    .map_err(|error| error.to_string())?;
                let sink = AppSink::builder()
                    .name("desklink-screen-sink")
                    .caps(&raw_caps)
                    .max_buffers(2)
                    .sync(false)
                    .build();
                let sample_events = events.clone();
                sink.set_callbacks(
                    AppSinkCallbacks::builder()
                        .new_sample(move |sink| {
                            let sample = sink.pull_sample().map_err(|_| gst::FlowError::Eos)?;
                            let caps = sample.caps().ok_or(gst::FlowError::NotNegotiated)?;
                            let structure =
                                caps.structure(0).ok_or(gst::FlowError::NotNegotiated)?;
                            let width = structure
                                .get::<i32>("width")
                                .map_err(|_| gst::FlowError::NotNegotiated)?;
                            let height = structure
                                .get::<i32>("height")
                                .map_err(|_| gst::FlowError::NotNegotiated)?;
                            let buffer = sample.buffer().ok_or(gst::FlowError::NotNegotiated)?;
                            let map = buffer.map_readable().map_err(|_| gst::FlowError::Error)?;
                            if let Some(events) = sample_events.as_ref() {
                                events(PeerEvent::VideoFrame {
                                    sequence: frame_sequence.fetch_add(1, Ordering::Relaxed) + 1,
                                    width: width.max(0) as u32,
                                    height: height.max(0) as u32,
                                    rgba: map.as_slice().to_vec(),
                                });
                            }
                            Ok(gst::FlowSuccess::Ok)
                        })
                        .build(),
                );
                pipeline
                    .add_many([&depay, &decoder, &convert, &filter, sink.upcast_ref()])
                    .map_err(|error| error.to_string())?;
                gst::Element::link_many([&depay, &decoder, &convert, &filter, sink.upcast_ref()])
                    .map_err(|error| error.to_string())?;
                let sink_pad = depay
                    .static_pad("sink")
                    .ok_or_else(|| "VP8 depayloader has no sink pad".to_string())?;
                pad.link(&sink_pad)
                    .map_err(|error| format!("Could not link incoming VP8 track: {error}"))?;
                depay
                    .sync_state_with_parent()
                    .map_err(|error| error.to_string())?;
                decoder
                    .sync_state_with_parent()
                    .map_err(|error| error.to_string())?;
                convert
                    .sync_state_with_parent()
                    .map_err(|error| error.to_string())?;
                filter
                    .sync_state_with_parent()
                    .map_err(|error| error.to_string())?;
                sink.upcast_ref::<gst::Element>()
                    .sync_state_with_parent()
                    .map_err(|error| error.to_string())?;
                Ok(())
            })();
            if let Err(error) = result {
                if let Some(events) = events.as_ref() {
                    events(PeerEvent::Failure(format!(
                        "Could not attach incoming VP8 screen track: {error}"
                    )));
                }
            }
        });
    }

    fn install_channel(&self, channel: WebRTCDataChannel) -> Result<(), ChannelError> {
        install_channel_into(&self.channels, self.events.clone(), channel)
    }

    pub fn close(&self) {
        self.stop_screen_capture();
        if let Ok(channels) = self.channels.lock() {
            for channel in channels.values() {
                channel.close();
            }
        }
        if let Some(pipeline) = &self.pipeline {
            let _ = pipeline.set_state(gst::State::Null);
        }
        let _ = self.element.set_state(gst::State::Null);
    }
}

fn install_channel_into(
    channels: &Arc<Mutex<HashMap<String, WebRTCDataChannel>>>,
    events: Option<PeerEventSink>,
    channel: WebRTCDataChannel,
) -> Result<(), ChannelError> {
    let label = channel
        .label()
        .map(|label| label.to_string())
        .ok_or_else(|| ChannelError::UnknownLabel("missing label".to_string()))?;
    let retransmits = match channel.max_retransmits() {
        -1 => None,
        value => Some(
            u16::try_from(value).map_err(|_| ChannelError::InvalidReliability(label.clone()))?,
        ),
    };
    DataChannelSpec::validate_remote(&label, channel.is_ordered(), retransmits)?;
    let open_events = events.clone();
    let open_label = label.clone();
    channel.connect_on_open(move |_| {
        if open_label == DataChannelSpec::CONTROL.label {
            if let Some(events) = open_events.as_ref() {
                events(PeerEvent::ControlChannelOpen);
            }
        }
    });
    let error_label = label.clone();
    let message_label = label.clone();
    let message_events = events.clone();
    channel.connect_on_message_data(move |_, bytes| {
        if let (Some(bytes), Some(events)) = (bytes, message_events.as_ref()) {
            events(PeerEvent::Message {
                channel: message_label.clone(),
                bytes: bytes.as_ref().to_vec(),
            });
        }
    });
    channel.connect_on_error(move |_, error| {
        if let Some(events) = events.as_ref() {
            events(PeerEvent::Failure(format!(
                "data channel {error_label} failed: {error}"
            )));
        }
    });
    channels
        .lock()
        .map_err(|_| ChannelError::UnknownLabel("channel map poisoned".to_string()))?
        .insert(label, channel);
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::mpsc;
    use std::time::{Duration, Instant};

    #[test]
    fn webrtcbin_is_available_on_this_runtime() {
        gst::init().unwrap();
        let element = gst::ElementFactory::make("webrtcbin")
            .name("desklink-test-webrtcbin")
            .build()
            .expect("GStreamer WebRTC plugin is required by desktop builds");
        let peer = PeerConnection::new(element);
        // Channel creation belongs to an active, negotiated pipeline. The
        // construction test keeps CI independent of a live network peer.
        peer.close();
    }

    #[test]
    fn rejects_oversized_sdp_before_gstreamer_parses_it() {
        gst::init().unwrap();
        let element = gst::ElementFactory::make("webrtcbin").build().unwrap();
        let peer = PeerConnection::new(element);
        assert!(peer.accept_answer(&"x".repeat(256 * 1024 + 1)).is_err());
    }

    /// Native runtime smoke test for the exact SDP/ICE/data-channel callbacks
    /// used by the desktop coordinator. It is opt-in because it opens local
    /// ICE sockets and requires the installed GStreamer WebRTC runtime.
    #[test]
    #[ignore = "requires a native GStreamer WebRTC loopback runtime"]
    fn desktop_data_channels_negotiate_over_loopback() {
        let (sender, receiver) = mpsc::channel::<(char, PeerEvent)>();
        let initiator_sender = sender.clone();
        let initiator = Arc::new(
            PeerConnection::new_negotiated(Arc::new(move |event| {
                let _ = initiator_sender.send(('a', event));
            }))
            .unwrap(),
        );
        let responder_sender = sender.clone();
        let responder = Arc::new(
            PeerConnection::new_negotiated(Arc::new(move |event| {
                let _ = responder_sender.send(('b', event));
            }))
            .unwrap(),
        );

        initiator.create_channels().unwrap();
        initiator.start_offer().unwrap();

        let mut initiator_open = false;
        let mut responder_open = false;
        let deadline = Instant::now() + Duration::from_secs(15);
        while Instant::now() < deadline && !(initiator_open && responder_open) {
            let Ok((side, event)) = receiver.recv_timeout(Duration::from_millis(250)) else {
                continue;
            };
            match (side, event) {
                ('a', PeerEvent::Offer(sdp)) => {
                    responder.accept_offer_and_create_answer(&sdp).unwrap()
                }
                ('b', PeerEvent::Answer(sdp)) => initiator.accept_answer(&sdp).unwrap(),
                (
                    'a',
                    PeerEvent::IceCandidate {
                        mline_index,
                        candidate,
                    },
                ) => responder
                    .add_ice_candidate(mline_index, &candidate)
                    .unwrap(),
                (
                    'b',
                    PeerEvent::IceCandidate {
                        mline_index,
                        candidate,
                    },
                ) => initiator
                    .add_ice_candidate(mline_index, &candidate)
                    .unwrap(),
                ('a', PeerEvent::ControlChannelOpen) => initiator_open = true,
                ('b', PeerEvent::ControlChannelOpen) => responder_open = true,
                (_, PeerEvent::EndOfCandidates) => {}
                (_, PeerEvent::Failure(error)) => panic!("native WebRTC loopback failed: {error}"),
                _ => {}
            }
        }
        initiator.close();
        responder.close();
        assert!(
            initiator_open && responder_open,
            "WebRTC control channel did not open before the loopback deadline"
        );
    }
}
